## -------------------------- ##
## 编码格式要求 UTF-8         ##
## -------------------------- ##
spring: 
  profiles: 
    active: 
      - dev
---
# 开发环境
spring:
  profiles: dev
  application: 
    name: config-dev
---
# 测试环境
spring:
  profiles: test
  application:
    name: config-test
